MDScreen:
    name: "enforcer_report_history"
    
    MDFloatLayout:
        md_bg_color: 1, 1, 1, 1
        
        MDIconButton:
            icon: "arrow-left"
            pos_hint: {"center_y": 0.95}
            user_font_size: "30sp"
            theme_text_color: "Custom"
            text_color: 26/255, 24/255, 58/255, 255/255
            on_release:
                root.manager.transition.direction = "right"
                root.manager.current = "homescreen_enforcer"